//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodToNow
    {
        public long id { get; set; }
        public string CheckIn { get; set; }
        public string CheckOut { get; set; }
        public string Pets { get; set; }
        public string Groups { get; set; }
        public Nullable<long> HotelId { get; set; }
        public string pricing { get; set; }
    }
}
