//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public string id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string zip { get; set; }
        public string city_hotel { get; set; }
        public string cc1 { get; set; }
        public string ufi { get; set; }
        public string @class { get; set; }
        public string currencycode { get; set; }
        public string minrate { get; set; }
        public string maxrate { get; set; }
        public string preferred { get; set; }
        public string nr_rooms { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string public_ranking { get; set; }
        public string hotel_url { get; set; }
        public string photo_url { get; set; }
        public string desc_en { get; set; }
        public string desc_fr { get; set; }
        public string desc_es { get; set; }
        public string desc_de { get; set; }
        public string desc_nl { get; set; }
        public string desc_it { get; set; }
        public string desc_pt { get; set; }
        public string desc_ja { get; set; }
        public string desc_zh { get; set; }
        public string desc_pl { get; set; }
        public string desc_ru { get; set; }
        public string desc_sv { get; set; }
        public string desc_ar { get; set; }
        public string desc_el { get; set; }
        public string desc_no { get; set; }
        public string city_unique { get; set; }
        public string city_preferred { get; set; }
        public string continent_id { get; set; }
        public string review_score { get; set; }
        public string review_nr { get; set; }
        public long HotelId { get; set; }
        public string DescriptionSite { get; set; }
        public Nullable<int> IsRecive { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Addresnew { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string stars { get; set; }
        public Nullable<long> countryid { get; set; }
        public Nullable<long> AccommodationlID { get; set; }
    }
}
