//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class logHotel
    {
        public long userLogID { get; set; }
        public Nullable<long> HotelID { get; set; }
        public string Exception { get; set; }
        public string line { get; set; }
        public string Description { get; set; }
    }
}
