//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapAccommodationBookingHotel
    {
        public long Id { get; set; }
        public Nullable<long> AccommodationId { get; set; }
        public Nullable<long> BookingId { get; set; }
        public string UrlPath { get; set; }
    }
}
