//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationLogTable
    {
        public int Id { get; set; }
        public long AccommodationID { get; set; }
        public Nullable<long> OldCityId { get; set; }
        public Nullable<long> NewCityId { get; set; }
        public string OldCountryCode { get; set; }
        public string NewCountryCode { get; set; }
        public string OldCityName { get; set; }
        public string NewCityName { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
