//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mgh_Air
    {
        public long AirCode { get; set; }
        public string City_name { get; set; }
        public string Airport_Code { get; set; }
        public string Airport_Name { get; set; }
        public string Country_name { get; set; }
        public string Country_Abbrev { get; set; }
        public string World_Area_Code { get; set; }
    }
}
