//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapDbContext : DbContext
    {
        public MapDbContext()
            : base("name=MapDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acc_Airport> Acc_Airport { get; set; }
        public virtual DbSet<AccommodationAlternativeName> AccommodationAlternativeNames { get; set; }
        public virtual DbSet<AccommodationLocationTmp> AccommodationLocationTmps { get; set; }
        public virtual DbSet<AccommodationLogTable> AccommodationLogTables { get; set; }
        public virtual DbSet<AccommodationproviderXml> AccommodationproviderXmls { get; set; }
        public virtual DbSet<AccommodationTmp> AccommodationTmps { get; set; }
        public virtual DbSet<AccommodationTmp2> AccommodationTmp2 { get; set; }
        public virtual DbSet<AccomodationSupplier2Tmp> AccomodationSupplier2Tmp { get; set; }
        public virtual DbSet<AccomodationSupplierTmp> AccomodationSupplierTmps { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<DeActiveAccommodation> DeActiveAccommodations { get; set; }
        public virtual DbSet<LocationHotelsBed> LocationHotelsBeds { get; set; }
        public virtual DbSet<LocationLogTb> LocationLogTbs { get; set; }
        public virtual DbSet<LocationTmp> LocationTmps { get; set; }
        public virtual DbSet<LocationTmp2> LocationTmp2 { get; set; }
        public virtual DbSet<Mgh_Air> Mgh_Air { get; set; }
        public virtual DbSet<TblB> TblBs { get; set; }
        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<AccommodationAirport> AccommodationAirports { get; set; }
        public virtual DbSet<AccommodationDiff> AccommodationDiffs { get; set; }
        public virtual DbSet<AccommodationLocation> AccommodationLocations { get; set; }
        public virtual DbSet<AccommodationTmp951109> AccommodationTmp951109 { get; set; }
        public virtual DbSet<AccomodationSupplier> AccomodationSuppliers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationInfo> LocationInfoes { get; set; }
    }
}
