//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationReview
    {
        public long AccommodationReviewID { get; set; }
        public long AccommodationID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<float> Rate { get; set; }
        public string ReviewText { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
    }
}
