//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationAttribute
    {
        public long AccommodationAttributeID { get; set; }
        public Nullable<long> AccommodationID { get; set; }
        public string Titel { get; set; }
        public Nullable<double> IRRPercent { get; set; }
        public Nullable<double> NokPercent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTag { get; set; }
        public long SupplierID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual Accommodation Accommodation { get; set; }
    }
}
