//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationCommission
    {
        public long AccommodationCommissionID { get; set; }
        public long LocationID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> AccommodationID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool Active { get; set; }
        public Nullable<double> IRRPercent { get; set; }
        public Nullable<double> NokPercent { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual Company1 Company1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
    }
}
