//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation_Booking4
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> HotelID { get; set; }
        public string Hotel_Url { get; set; }
        public string BookingNewLatitude { get; set; }
        public string BookingNewLongitude { get; set; }
        public string BookingLatitude { get; set; }
        public string BookingLongitude { get; set; }
        public Nullable<long> AccommodationlID { get; set; }
        public string AccommodationLatitude { get; set; }
        public string AccommodationLongitude { get; set; }
        public Nullable<long> IsRecive { get; set; }
    }
}
