//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomodationRoomImage
    {
        public long AccomodationRoomImageID { get; set; }
        public long AccommodationID { get; set; }
        public long RoomTypeId { get; set; }
        public string RoomTypeName { get; set; }
        public string RoomTypeIcon { get; set; }
        public string RoomTypeIconInfo { get; set; }
        public string RoomTypeInfo { get; set; }
        public string RoomImagePhysicalPath { get; set; }
        public string RoomImgUrl { get; set; }
        public Nullable<int> Radif { get; set; }
        public string RoomSize { get; set; }
        public string RoomFacilities { get; set; }
        public string RoomDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public string OriginalLink { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public Nullable<bool> IsReported { get; set; }
        public Nullable<int> NumberOfReports { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
    }
}
