//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomodatonContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccomodatonContract()
        {
            this.AccomodationVouchers = new HashSet<AccomodationVoucher>();
        }
    
        public long AccomodationContractID { get; set; }
        public long ContractID { get; set; }
        public string RPHKey_Old { get; set; }
        public string RPH { get; set; }
        public string VocherRefrence { get; set; }
        public string HotelReservName { get; set; }
        public Nullable<decimal> TotalFare { get; set; }
        public string TotalFareCurrencyCode { get; set; }
        public Nullable<decimal> TotalCommission { get; set; }
        public string TotalCommissionCurrencyCode { get; set; }
        public Nullable<decimal> CounterCommission { get; set; }
        public string CounterCommissionCurrencyCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<long> TicketStatusID { get; set; }
        public string RPHKey { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<System.DateTime> Nights { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string AccommodationAddress { get; set; }
        public string SupplierName { get; set; }
        public string RatePlanCode { get; set; }
        public string BillVocher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccomodationVoucher> AccomodationVouchers { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
