//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomodationImage
    {
        public long ImageID { get; set; }
        public long AccommodationlID { get; set; }
        public byte Type { get; set; }
        public string ThumbnailLink { get; set; }
        public string Link { get; set; }
        public Nullable<long> AccomodationSupplierID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public string OriginalLink { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
    }
}
