//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationDescription
    {
        public long AccommodationDescriptionID { get; set; }
        public Nullable<long> AccommodationID { get; set; }
        public Nullable<long> LanguageID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual Language Language { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
    }
}
