//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationMap3
    {
        public long AccommodationlID { get; set; }
        public Nullable<long> ChainID { get; set; }
        public string AirportCode { get; set; }
        public Nullable<byte> Type { get; set; }
        public string Name { get; set; }
        public string Rating { get; set; }
        public string Address { get; set; }
        public string PostCodeZip { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Description { get; set; }
        public string Near { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string CountryCode { get; set; }
        public string CityName { get; set; }
        public Nullable<long> CityId { get; set; }
        public Nullable<int> Resort { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<long> DestinationId { get; set; }
        public string Destination { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> HotelArea { get; set; }
        public Nullable<int> HotelImages { get; set; }
        public Nullable<int> HotelLocation { get; set; }
        public Nullable<int> HotelInfo { get; set; }
        public Nullable<int> PAmenities { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public int IsActive { get; set; }
    }
}
