//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomodationVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccomodationVoucher()
        {
            this.VoucherRooms = new HashSet<VoucherRoom>();
        }
    
        public long AccomodationContractID { get; set; }
        public long AccomodationVocherID { get; set; }
        public string Vocher { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual AccomodatonContract AccomodatonContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherRoom> VoucherRooms { get; set; }
    }
}
