//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        public int ID { get; set; }
        public string IATACode { get; set; }
        public string Manufacturer { get; set; }
        public string TypeModel { get; set; }
        public string Wake { get; set; }
    }
}
