//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineSupplierWhitelist
    {
        public long AirlineSupplierWhitelistID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> AirlineID { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public byte Type { get; set; }
        public bool Active { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User1 User11 { get; set; }
    }
}
