//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportSupplierConfig
    {
        public long AirportSupplierConfigID { get; set; }
        public long AirlineID { get; set; }
        public Nullable<long> AirportID { get; set; }
        public long SupplierID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
        public bool Active { get; set; }
        public Nullable<double> IRRPercent { get; set; }
        public Nullable<double> NokPercent { get; set; }
        public Nullable<bool> Special { get; set; }
        public Nullable<double> TicketIRRPercent { get; set; }
        public Nullable<double> TicketNokPercent { get; set; }
        public string FareBasis { get; set; }
        public string CabinClasses { get; set; }
        public string PriceCenter { get; set; }
        public string MinStay { get; set; }
        public string MaxStay { get; set; }
    }
}
