//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long Answer_id { get; set; }
        public Nullable<long> Language_id { get; set; }
        public Nullable<long> User_id { get; set; }
        public Nullable<System.DateTime> Date_answered { get; set; }
        public string Answer_text { get; set; }
        public long Question_id { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Question Question { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
