//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailHotelCode
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AccessDateTime { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> LocationTypeId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string HotelCode { get; set; }
    }
}
