//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public long BillID { get; set; }
        public string AttachName { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<long> CreatorID { get; set; }
    
        public virtual User1 User1 { get; set; }
    }
}
