//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHotelTemp
    {
        public long hotelId { get; set; }
        public string HotelName { get; set; }
        public string City { get; set; }
        public string Url { get; set; }
        public Nullable<long> CityId { get; set; }
        public long CountryId { get; set; }
    }
}
