//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySupplierAccess
    {
        public long CompanyID { get; set; }
        public long SupplierID { get; set; }
        public bool Shopping { get; set; }
        public bool Pricing { get; set; }
        public bool Ticketing { get; set; }
        public Nullable<float> MarkupPercent { get; set; }
        public Nullable<float> CommissionPercent { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
