//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyWhiteLabelConfig
    {
        public long CompanyWhiteLabelConfigID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Companyname { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
        public bool Active { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
