//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long ContactID { get; set; }
        public Nullable<bool> Title { get; set; }
        public string GivenName { get; set; }
        public string SureName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string DocumentID { get; set; }
        public string DocumentType { get; set; }
        public Nullable<System.DateTime> DocumentExpire { get; set; }
        public string NationalID { get; set; }
        public bool IsPartner { get; set; }
        public string ImageLink { get; set; }
    }
}
