//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public long ContactUs_id { get; set; }
        public string Title { get; set; }
        public string description { get; set; }
        public string Name { get; set; }
        public string Email_address { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string organization { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string postal_code { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public Nullable<long> state_id { get; set; }
        public Nullable<int> WebSiteID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
