//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contacts1()
        {
            this.AccomodatonContractPassengers = new HashSet<AccomodatonContractPassenger>();
            this.Addresses = new HashSet<Address>();
            this.FlightContractPassengers = new HashSet<FlightContractPassenger>();
            this.InsuranceTickets = new HashSet<InsuranceTicket>();
            this.RequestObjects = new HashSet<RequestObject>();
            this.RequestTours = new HashSet<RequestTour>();
            this.Telephones = new HashSet<Telephone>();
            this.TelephoneUs = new HashSet<TelephoneU>();
            this.User1 = new HashSet<User1>();
        }
    
        public long ContactID { get; set; }
        public Nullable<bool> Title { get; set; }
        public string GivenName { get; set; }
        public string SureName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string DocumentID { get; set; }
        public string DocumentType { get; set; }
        public Nullable<System.DateTime> DocumentExpire { get; set; }
        public string NationalID { get; set; }
        public bool IsPartner { get; set; }
        public string ImageLink { get; set; }
        public Nullable<System.DateTime> PassportExpiry { get; set; }
        public string nationalcode { get; set; }
        public string PassportNo { get; set; }
        public string PassengerType { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<byte> ContactType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccomodatonContractPassenger> AccomodatonContractPassengers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightContractPassenger> FlightContractPassengers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceTicket> InsuranceTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestObject> RequestObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestTour> RequestTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telephone> Telephones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelephoneU> TelephoneUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User1> User1 { get; set; }
    }
}
