//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public long CountryID { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string Area { get; set; }
        public Nullable<long> CurrencyID { get; set; }
    }
}
