//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryNationality
    {
        public string CountryNationalityID { get; set; }
        public string CountryName { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> DotwCode { get; set; }
        public string HotelsBedNationalityCode { get; set; }
        public string HotelsBedCountryCode { get; set; }
        public string ExpediaCode { get; set; }
    }
}
