//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeActiveAccommodation
    {
        public int Id { get; set; }
        public long AccommodationlD { get; set; }
        public Nullable<int> Counter { get; set; }
        public bool ISDeactive { get; set; }
        public Nullable<long> MovedToAccommodationlD { get; set; }
    }
}
