//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevelopmentRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevelopmentRequest()
        {
            this.DevelopmentRequestDetails = new HashSet<DevelopmentRequestDetail>();
            this.DevelopmentRequestFiles = new HashSet<DevelopmentRequestFile>();
            this.DevelopmentRequest1 = new HashSet<DevelopmentRequest>();
        }
    
        public long DevelopmentRequestID { get; set; }
        public Nullable<long> ParentTicketID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<long> FromID { get; set; }
        public Nullable<long> ToID { get; set; }
        public Nullable<int> Status { get; set; }
        public string GroupID { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevelopmentRequestDetail> DevelopmentRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevelopmentRequestFile> DevelopmentRequestFiles { get; set; }
        public virtual User1 User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevelopmentRequest> DevelopmentRequest1 { get; set; }
        public virtual DevelopmentRequest DevelopmentRequest2 { get; set; }
        public virtual User1 User11 { get; set; }
        public virtual User1 User12 { get; set; }
        public virtual User1 User13 { get; set; }
    }
}
