//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discount()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public long DiscountID { get; set; }
        public string DiscountCode { get; set; }
        public string DiscountDescription { get; set; }
        public Nullable<System.DateTime> DiscountFromDateTime { get; set; }
        public Nullable<System.DateTime> DiscountToDateTime { get; set; }
        public Nullable<byte> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<byte> DiscountType { get; set; }
        public byte DiscountStatus { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> UserID { get; set; }
        public long CurrencyID { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<byte> DiscountInUse { get; set; }
        public Nullable<long> AccommodationId { get; set; }
        public string Rating { get; set; }
        public Nullable<long> LocationID { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Location Location { get; set; }
        public virtual User1 User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Accommodation Accommodation { get; set; }
    }
}
