//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeDetails_970317
    {
        public long ExchangeDetailID { get; set; }
        public long ExchangeID { get; set; }
        public decimal ROE { get; set; }
        public long UserID { get; set; }
        public long SupplierID { get; set; }
        public System.DateTime CreationTime { get; set; }
    }
}
