//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility1
    {
        public long ID { get; set; }
        public Nullable<long> FacilityID { get; set; }
        public Nullable<long> FacilityGroupID { get; set; }
        public string FacilityGroup { get; set; }
        public string FacilityType { get; set; }
        public string Facility { get; set; }
    }
}
