//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightEticket
    {
        public long FlightEticketID { get; set; }
        public long FlightTicketID { get; set; }
        public string EticketID { get; set; }
    
        public virtual FlightTicket FlightTicket { get; set; }
    }
}
