//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightTicketInformation
    {
        public long FlightTicketInformationID { get; set; }
        public long FlightTicketID { get; set; }
        public string InformationGiveName { get; set; }
        public string InformationSureName { get; set; }
        public string InformationAddress { get; set; }
        public string InformationTelephoneNumber { get; set; }
        public string InformationEmail { get; set; }
        public string InformationOrigin { get; set; }
        public string InformationDestination { get; set; }
        public string InformationDeparture { get; set; }
        public string InformationReturn { get; set; }
        public string InformationAirLineName { get; set; }
        public string NumberOfPassenger { get; set; }
    }
}
