//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightTicket()
        {
            this.FlightEtickets = new HashSet<FlightEticket>();
            this.FlightTicketArrivals = new HashSet<FlightTicketArrival>();
            this.FlightTicketDepartures = new HashSet<FlightTicketDeparture>();
            this.FlightTicketFareBreakdowns = new HashSet<FlightTicketFareBreakdown>();
            this.FlightTicketNotArrivals = new HashSet<FlightTicketNotArrival>();
            this.FlightTicketNotDepartures = new HashSet<FlightTicketNotDeparture>();
            this.FlightTicketTaxesFareBreakdowns = new HashSet<FlightTicketTaxesFareBreakdown>();
            this.PaymentTickets = new HashSet<PaymentTicket>();
        }
    
        public long FlightTicketID { get; set; }
        public long FlightContractID { get; set; }
        public string Ticket { get; set; }
        public string TicketNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string PassengerType { get; set; }
        public Nullable<int> Age { get; set; }
        public string FlightNumber { get; set; }
        public string Cabin { get; set; }
        public Nullable<int> BaggageAllowance { get; set; }
        public Nullable<decimal> BaseFareAmount { get; set; }
        public string BaseFareCurrency { get; set; }
        public Nullable<decimal> FareTaxAmount { get; set; }
        public string FareTaxCurrency { get; set; }
        public Nullable<decimal> EquivFareAmount { get; set; }
        public string EquivFareCurrency { get; set; }
        public Nullable<decimal> TotalFareAmount { get; set; }
        public string TotalFareCurrency { get; set; }
        public string FareCalculation { get; set; }
        public string DepartDate { get; set; }
        public string Dest { get; set; }
        public string Origin { get; set; }
        public string NotValidAfter { get; set; }
        public string FareBasis { get; set; }
        public string AccountingCode { get; set; }
        public string IssueDate { get; set; }
        public string IssuingAgent { get; set; }
        public Nullable<decimal> CashCheckAMount { get; set; }
        public string PaymentForm { get; set; }
        public string ItineraryCode { get; set; }
        public string PrintStation { get; set; }
        public string TicketInternalNo { get; set; }
        public string UnsuccessMessage { get; set; }
        public Nullable<int> Status { get; set; }
        public string Carrier { get; set; }
        public string PayStatus { get; set; }
        public string CompleteBy { get; set; }
        public string CompleteDate { get; set; }
        public string Attach { get; set; }
        public string GDS { get; set; }
        public string PCC { get; set; }
        public string Commission { get; set; }
        public string ExchangeRate { get; set; }
        public string Markup { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> PNRID { get; set; }
        public string AirLineRef { get; set; }
        public string PNRCode { get; set; }
        public string GiveName { get; set; }
        public string SureName { get; set; }
        public string CityName { get; set; }
        public string BookingReferenceID { get; set; }
        public string PaymentNumbers { get; set; }
        public string BookingDate { get; set; }
        public string CompanyImage { get; set; }
        public string CompanyName { get; set; }
        public string Departure { get; set; }
        public string Change { get; set; }
        public Nullable<decimal> FareFeeAmount { get; set; }
        public string FareFeeCurrency { get; set; }
    
        public virtual FlightContract FlightContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightEticket> FlightEtickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightTicketArrival> FlightTicketArrivals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightTicketDeparture> FlightTicketDepartures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightTicketFareBreakdown> FlightTicketFareBreakdowns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightTicketNotArrival> FlightTicketNotArrivals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightTicketNotDeparture> FlightTicketNotDepartures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightTicketTaxesFareBreakdown> FlightTicketTaxesFareBreakdowns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentTicket> PaymentTickets { get; set; }
    }
}
