//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightTicketFareBreakdown
    {
        public long FlightTicketFareBreakdownID { get; set; }
        public long FlightTicketID { get; set; }
        public string FareBreakdownCode { get; set; }
        public string FareBreakdownBaseFare { get; set; }
        public string FareBreakdownFlightTaxes { get; set; }
        public string FareBreakdownFlightFees { get; set; }
        public string FareBreakdownTotal { get; set; }
        public string EquivalentFare { get; set; }
    
        public virtual FlightTicket FlightTicket { get; set; }
    }
}
