//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightIndex
    {
        public long PackageIndexID { get; set; }
        public Nullable<int> TypeIndex { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string FromLocationID { get; set; }
        public string ToLocationID { get; set; }
        public string DepartureDate { get; set; }
        public string ReturnDate { get; set; }
        public Nullable<int> Night { get; set; }
        public string HtelMarkup { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<long> HotelRate { get; set; }
        public string FlightMarkup { get; set; }
        public string CabinID { get; set; }
        public string AirlineID { get; set; }
        public Nullable<bool> Ionly { get; set; }
        public string Checkin { get; set; }
        public string Checkout { get; set; }
        public Nullable<bool> Nonstop { get; set; }
        public Nullable<bool> Multiticket { get; set; }
        public string NationalityID { get; set; }
        public Nullable<bool> Allinclusive { get; set; }
        public Nullable<bool> BedBreakfast { get; set; }
        public string DepartureTime { get; set; }
        public string ReturnTime { get; set; }
        public string ModificationDateTime { get; set; }
        public string ModificationUserID { get; set; }
        public string CreateDateTime { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public string HotelName { get; set; }
        public Nullable<decimal> FromPrice { get; set; }
        public Nullable<decimal> ToPrice { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> PackageFromDate { get; set; }
        public Nullable<System.DateTime> PackageToDate { get; set; }
        public string Airtriptype { get; set; }
        public string Origintext { get; set; }
        public string Destinationtext { get; set; }
        public string Title_EN { get; set; }
        public Nullable<long> LanguageID { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.DateTime> ScheduledToRunOn { get; set; }
        public string TaskActionUrl { get; set; }
        public Nullable<long> CompanyID { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual Language Language { get; set; }
    }
}
