//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightDiscount
    {
        public long DiscountID { get; set; }
        public System.DateTime FromDateTime { get; set; }
        public System.DateTime ToDateTime { get; set; }
        public long SupplierID { get; set; }
        public long AirlineID { get; set; }
        public byte DiscountPercent { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
