//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC
    {
        public int ID { get; set; }
        public string code { get; set; }
        public string CityName { get; set; }
        public string CityNameGC { get; set; }
        public string CityId { get; set; }
    }
}
