//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCMAPXmlNode
    {
        public long ID { get; set; }
        public Nullable<long> GCMAPID { get; set; }
        public string NodeName { get; set; }
        public string NodeValue { get; set; }
        public string RPH { get; set; }
    }
}
