//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCMAPOld
    {
        public long GCMAPID { get; set; }
        public string Name { get; set; }
        public string code { get; set; }
        public string CityName { get; set; }
        public string CountryName { get; set; }
        public string Type { get; set; }
        public string Uses { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string innerT { get; set; }
        public string innerH { get; set; }
    }
}
