//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetHotelAvailInfo
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> AccessDateTime { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> LocationTypeID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string TableDatax { get; set; }
        public string Locations { get; set; }
    }
}
