//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gtaHotelInfoOnly
    {
        public string CityName { get; set; }
        public string CityCode { get; set; }
        public string HotelName { get; set; }
        public string HotelCode { get; set; }
        public string ADDRESSLine1 { get; set; }
        public string ADDRESSLine2 { get; set; }
        public string ADDRESSLine3 { get; set; }
        public string Telephone { get; set; }
        public string Website { get; set; }
        public string StarRating { get; set; }
        public string Category { get; set; }
        public string Reports { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string FacilityCode { get; set; }
        public string FacilityName { get; set; }
        public int Id { get; set; }
    }
}
