//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class gtaLocationData_970313
    {
        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string Citycode { get; set; }
        public string CityName { get; set; }
        public string CitiesArray { get; set; }
        public Nullable<long> LocationID { get; set; }
        public string MyCountryName { get; set; }
    }
}
