//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help1
    {
        public long HelpId { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public string HelpText { get; set; }
    }
}
