//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelLatLong
    {
        public long id { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<long> HotelId { get; set; }
    }
}
