//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingStaticDataEntities : DbContext
    {
        public BookingStaticDataEntities()
            : base("name=BookingStaticDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<GoodToNow> GoodToNows { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelLatLong> HotelLatLongs { get; set; }
        public virtual DbSet<ImgUrl> ImgUrls { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<RoomInfo> RoomInfoes { get; set; }
    }
}
