//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox2
    {
        public int InboxID { get; set; }
        public long FromUserID { get; set; }
        public Nullable<long> ToUserID { get; set; }
        public System.DateTime Created { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsRead { get; set; }
        public bool IsReceived { get; set; }
        public bool IsSent { get; set; }
        public bool IsStar { get; set; }
        public bool IsTrash { get; set; }
        public bool IsDraft { get; set; }
        public int Type { get; set; }
        public System.Guid GuidPk { get; set; }
        public Nullable<bool> IR { get; set; }
    }
}
