//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceContract()
        {
            this.InsuranceTickets = new HashSet<InsuranceTicket>();
        }
    
        public long InsuranceContractID { get; set; }
        public long ContractID { get; set; }
        public string InsuranceRPHKey { get; set; }
        public string InsuranceRPH { get; set; }
        public Nullable<decimal> TotalFare { get; set; }
        public Nullable<decimal> TotalBaseFare { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalCommission { get; set; }
        public string Destination { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<long> CurrencyID { get; set; }
        public Nullable<int> PassengerQty { get; set; }
        public Nullable<int> ZoneCode { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Location Location { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceTicket> InsuranceTickets { get; set; }
    }
}
