//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCountry
    {
        public int Id { get; set; }
        public string EN_CountryName { get; set; }
        public string FA_CountryName { get; set; }
        public string CountryId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> LocationId2 { get; set; }
    }
}
