//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceTicket
    {
        public long InsuranceTicketID { get; set; }
        public long InsuranceContractID { get; set; }
        public string Ticket { get; set; }
        public string InsuranceCode { get; set; }
        public string InsuranceTicketNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> ContactID { get; set; }
        public string BillInsuranceTicket { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
    
        public virtual Contacts1 Contacts1 { get; set; }
        public virtual InsuranceContract InsuranceContract { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
    }
}
