//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuanceData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssuanceData()
        {
            this.PaymentLists = new HashSet<PaymentList>();
            this.Ticketings = new HashSet<Ticketing>();
        }
    
        public int IssuanceDataId { get; set; }
        public string AgentSine { get; set; }
        public string DocumentType { get; set; }
        public string DomesticInternational { get; set; }
        public string IndicatorTwo { get; set; }
        public string IssueTime { get; set; }
        public string ItineraryRef { get; set; }
        public string PersonName { get; set; }
        public string StockItemCount { get; set; }
        public string TicketPrinter { get; set; }
        public string TicketStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentList> PaymentLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticketing> Ticketings { get; set; }
    }
}
