//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localize
    {
        public long LocalizeID { get; set; }
        public long LocationID { get; set; }
        public Nullable<byte> Calendar { get; set; }
        public long LanguageID { get; set; }
        public long CurrencyID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual Location Location { get; set; }
    }
}
