//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSupplier
    {
        public long LocationSupplierID { get; set; }
        public long LocationlID { get; set; }
        public long SupplierID { get; set; }
        public string Code { get; set; }
        public bool Active { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
