//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public long LoginLogID { get; set; }
        public string Ip { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
    }
}
