//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public long MealID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string CategoryCode { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string SaberCode { get; set; }
        public bool SaberActive { get; set; }
        public string AirArabiaCode { get; set; }
        public bool AirArabiaActive { get; set; }
    }
}
