//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.MessagesMappeds = new HashSet<MessagesMapped>();
        }
    
        public long MessageID { get; set; }
        public string EmailAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> FromDatetime { get; set; }
        public Nullable<System.DateTime> ToDatetime { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessagesMapped> MessagesMappeds { get; set; }
    }
}
