//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesMapped
    {
        public long MessagesMappedID { get; set; }
        public Nullable<long> MessageID { get; set; }
        public Nullable<int> PlaceHolderID { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsStarred { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
    }
}
