//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MistakeName
    {
        public Nullable<long> LocationID { get; set; }
        public string MistakeName1 { get; set; }
        public long MistakeNameID { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
