//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentCard()
        {
            this.TransferContracts = new HashSet<TransferContract>();
        }
    
        public long PaymentCardid { get; set; }
        public string CardType { get; set; }
        public string CardCode { get; set; }
        public string CardNumber { get; set; }
        public string ExpireDate { get; set; }
        public Nullable<int> SeriesCode { get; set; }
        public string CardHolderName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferContract> TransferContracts { get; set; }
    }
}
