//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTicket
    {
        public long PyamentTicketID { get; set; }
        public long PaymentID { get; set; }
        public long FlightTicketID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long CurrencyID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public long CreationUser { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual FlightTicket FlightTicket { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
