//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentList
    {
        public int PaymentListId { get; set; }
        public int IssuanceDataId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
    
        public virtual IssuanceData IssuanceData { get; set; }
    }
}
