//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentTickets = new HashSet<PaymentTicket>();
            this.Wallets = new HashSet<Wallet>();
        }
    
        public long PaymentID { get; set; }
        public long CompanyID { get; set; }
        public long CurrencyID { get; set; }
        public long ContractID { get; set; }
        public string TransactionID { get; set; }
        public byte Status { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDateTime { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string Comment { get; set; }
        public string Image { get; set; }
        public Nullable<long> ReversedFromID { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public decimal Remain { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<long> DiscountID { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<byte> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
    
        public virtual Company1 Company1 { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual User1 User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentTicket> PaymentTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallets { get; set; }
    }
}
