//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonNameLists = new HashSet<PersonNameList>();
            this.TransferContracts = new HashSet<TransferContract>();
        }
    
        public long Personid { get; set; }
        public Nullable<long> TransferTelephoneid { get; set; }
        public Nullable<long> TransferAddressid { get; set; }
        public Nullable<long> Emailid { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual TransferAddress TransferAddress { get; set; }
        public virtual TransferTelephone TransferTelephone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonNameList> PersonNameLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferContract> TransferContracts { get; set; }
    }
}
