//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PNR()
        {
            this.PNR_RPH = new HashSet<PNR_RPH>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public long PNRID { get; set; }
        public string UserName { get; set; }
        public string Origin { get; set; }
        public string OriginTerminal { get; set; }
        public string OriginTerminalCode { get; set; }
        public string Destination { get; set; }
        public string DestinationTerminal { get; set; }
        public string DestinationTerminalCode { get; set; }
        public string ResBookDesigCode { get; set; }
        public Nullable<System.DateTime> DepartureDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public string AirMilesFlown { get; set; }
        public string AirEquipType { get; set; }
        public string FlightNumber { get; set; }
        public string MarketingAirline { get; set; }
        public string Meal { get; set; }
        public string OperatingAirline { get; set; }
        public string Status { get; set; }
        public string StopQuantity { get; set; }
        public string SupplierRef { get; set; }
        public string UpdatedArrivalTime { get; set; }
        public string UpdatedDepartureTime { get; set; }
        public string eTicketNumber { get; set; }
        public string TicketTimeLimit { get; set; }
        public string GivenName { get; set; }
        public string Surname { get; set; }
        public string PassengerType { get; set; }
        public string WithInfant { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string CreationAgent { get; set; }
        public string HomePseudoCityCode { get; set; }
        public string PseudoCityCode { get; set; }
        public string ReceivedFrom { get; set; }
        public string InhibitCode { get; set; }
        public string PartitionID { get; set; }
        public string PrimeHostID { get; set; }
        public string Cancel { get; set; }
        public Nullable<long> CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string GDS { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<bool> MainPassenger { get; set; }
        public string Code { get; set; }
        public string PnrFileHtml { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<byte> PnrType { get; set; }
        public byte PaymentStatus { get; set; }
    
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PNR_RPH> PNR_RPH { get; set; }
        public virtual User1 User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
