//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege_970421
    {
        public long PrivilegeID { get; set; }
        public Nullable<long> PrivilegeParentID { get; set; }
        public string Title { get; set; }
        public string EngTitle { get; set; }
        public Nullable<System.Guid> PrivilegeGuid { get; set; }
        public Nullable<System.Guid> PrivilegeParentIGuid { get; set; }
        public string ControllerName { get; set; }
        public Nullable<long> PrivilegeCode { get; set; }
    }
}
