//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RailwayContract
    {
        public long RailwayContractID { get; set; }
        public long ContractID { get; set; }
        public string RPH { get; set; }
        public Nullable<long> RailBookingRefrenceId { get; set; }
        public Nullable<decimal> TotalFare { get; set; }
        public string TotalFareCurrencyCode { get; set; }
        public Nullable<decimal> TotalCommission { get; set; }
        public string TotalCommissionCurrencyCode { get; set; }
        public Nullable<decimal> CounterCommission { get; set; }
        public string CounterCommissionCurrencyCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<long> RailStatusID { get; set; }
        public string RPHKey { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string RailAddress { get; set; }
        public string SupplierName { get; set; }
        public string RatePlanCode { get; set; }
        public string BillRailTicket { get; set; }
        public string RailTicket { get; set; }
        public string DepartureLocation { get; set; }
        public string ReturnLocation { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
