//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatePlanSupplier
    {
        public int RatePlanSupplierID { get; set; }
        public long RatePlanID { get; set; }
        public long SupplierID { get; set; }
        public string SupplierCode { get; set; }
    
        public virtual RatePlan RatePlan { get; set; }
    }
}
