//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTour
    {
        public long RequestTourID { get; set; }
        public Nullable<long> TourID { get; set; }
        public Nullable<long> ContactID { get; set; }
        public Nullable<byte> Qty { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<long> ContractID { get; set; }
    
        public virtual Contacts1 Contacts1 { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
