//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestUser
    {
        public long RequestUserId { get; set; }
        public string GivenName { get; set; }
        public string SureName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public Nullable<long> LanguageID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<long> CurrencyID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<long> ModifyUserID { get; set; }
        public byte Status { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
