//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReserveRefound
    {
        public long ReserveRefoundId { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ModifyUseID { get; set; }
        public byte CancelType { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public byte Status { get; set; }
        public string OwnerCartNumber { get; set; }
        public string OwnerCartName { get; set; }
        public string OwnerAccountNumber { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
    }
}
