//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePrivilege_970421
    {
        public long RolePrivilegeID { get; set; }
        public Nullable<long> RoleID { get; set; }
        public Nullable<long> PrivilegeID { get; set; }
    }
}
