//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_970414
    {
        public long RoleID { get; set; }
        public string Name { get; set; }
        public bool DefineCurrency { get; set; }
        public bool DefineExchange { get; set; }
        public bool FillExchange { get; set; }
        public bool DefineUser { get; set; }
        public bool DefineCompany { get; set; }
        public bool AddDeposite { get; set; }
    }
}
