//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLocation
    {
        public long ServiceLocationID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price_Per_Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Service Service { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
