//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceContract
    {
        public long ServiceContractID { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TotalAmountCurrencyCode { get; set; }
        public string ServiceRph { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Location Location { get; set; }
        public virtual Service Service { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
