//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionItemX
    {
        public long IDSessionItem { get; set; }
        public Nullable<System.DateTime> AccessDateTime { get; set; }
        public string RPH { get; set; }
        public string Key_Old { get; set; }
        public Nullable<System.Guid> KeyGUID { get; set; }
        public Nullable<System.Guid> ParentGUID { get; set; }
        public Nullable<System.Guid> ChildGUID { get; set; }
    }
}
