//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int id { get; set; }
        public string description { get; set; }
        public string constrained { get; set; }
        public string data_type { get; set; }
        public string min_value { get; set; }
        public string max_value { get; set; }
        public string value { get; set; }
    }
}
