//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialEquipPref
    {
        public long SpecialEquipPrefid { get; set; }
        public long TransferContractid { get; set; }
        public Nullable<int> EquipType { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual TransferContract TransferContract { get; set; }
    }
}
