//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public long SuggestionID { get; set; }
        public Nullable<int> TypeIndex { get; set; }
        public Nullable<int> Type { get; set; }
        public string CheckInDate { get; set; }
        public string CheckOutDate { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string SourceCode { get; set; }
        public string DestinationCode { get; set; }
        public string Link { get; set; }
        public Nullable<long> CurrencyID { get; set; }
        public Nullable<decimal> FromPrice { get; set; }
        public Nullable<decimal> ToPrice { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<long> LanguageID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreateDateTime { get; set; }
        public Nullable<long> CreateUserID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual User1 User1 { get; set; }
    }
}
