//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.AccommodationCommissions = new HashSet<AccommodationCommission>();
            this.AccommodationAttributes = new HashSet<AccommodationAttribute>();
            this.AccommodationCommission1 = new HashSet<AccommodationCommission1>();
            this.AccommodationItoursSuppliers = new HashSet<AccommodationItoursSupplier>();
            this.AccomodationSuppliers = new HashSet<AccomodationSupplier>();
            this.AirlineSupplierConfigs = new HashSet<AirlineSupplierConfig>();
            this.AirlineSupplierWhitelists = new HashSet<AirlineSupplierWhitelist>();
            this.AirportSuppliers = new HashSet<AirportSupplier>();
            this.AirportSupplierConfig1 = new HashSet<AirportSupplierConfig1>();
            this.CompanySupplierAccesses = new HashSet<CompanySupplierAccess>();
            this.FlightContracts = new HashSet<FlightContract>();
            this.FlightDiscounts = new HashSet<FlightDiscount>();
            this.InsuranceContracts = new HashSet<InsuranceContract>();
            this.LocationSuppliers = new HashSet<LocationSupplier>();
            this.PNR_RPH = new HashSet<PNR_RPH>();
            this.RailwayContracts = new HashSet<RailwayContract>();
        }
    
        public long SupplierID { get; set; }
        public byte SupplierType { get; set; }
        public string Name { get; set; }
        public string CompanyCode { get; set; }
        public string PseudoCityCode { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string AgentID { get; set; }
        public string Domain { get; set; }
        public string Url { get; set; }
        public bool IsTest { get; set; }
        public string UrlSecured { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccommodationCommission> AccommodationCommissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccommodationAttribute> AccommodationAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccommodationCommission1> AccommodationCommission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccommodationItoursSupplier> AccommodationItoursSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccomodationSupplier> AccomodationSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirlineSupplierConfig> AirlineSupplierConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirlineSupplierWhitelist> AirlineSupplierWhitelists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirportSupplier> AirportSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirportSupplierConfig1> AirportSupplierConfig1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanySupplierAccess> CompanySupplierAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightContract> FlightContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightDiscount> FlightDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceContract> InsuranceContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationSupplier> LocationSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PNR_RPH> PNR_RPH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RailwayContract> RailwayContracts { get; set; }
    }
}
