//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier960615
    {
        public long SupplierID { get; set; }
        public byte SupplierType { get; set; }
        public string Name { get; set; }
        public string CompanyCode { get; set; }
        public string PseudoCityCode { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string AgentID { get; set; }
        public string Domain { get; set; }
        public string Url { get; set; }
        public bool IsTest { get; set; }
        public string UrlSecured { get; set; }
    }
}
