//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAirPortAlirezaMap
    {
        public int ID { get; set; }
        public Nullable<long> AirportID { get; set; }
        public string Code { get; set; }
        public string IATA_location { get; set; }
        public string Name { get; set; }
        public string NameLong { get; set; }
        public string NameLong2 { get; set; }
        public string CountryCode { get; set; }
        public string destinationId { get; set; }
        public string DestinationCode { get; set; }
    }
}
