//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAllAirport
    {
        public long ID { get; set; }
        public string City_name { get; set; }
        public string City_code { get; set; }
        public string Airport_name { get; set; }
        public string airport_code { get; set; }
    }
}
