//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDiff
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string CityName { get; set; }
        public string Location2Name { get; set; }
        public string CountryName { get; set; }
        public string Location3Name { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> Rank { get; set; }
    }
}
