//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telephone
    {
        public long TelephoneID { get; set; }
        public long ContactID { get; set; }
        public string Number { get; set; }
        public Nullable<byte> Type { get; set; }
    
        public virtual Contacts1 Contacts1 { get; set; }
    }
}
