//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.RequestTours = new HashSet<RequestTour>();
        }
    
        public long TourID { get; set; }
        public string HotelName { get; set; }
        public string HotelRating { get; set; }
        public string HotelImages { get; set; }
        public string HotelInfo { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string CityName { get; set; }
        public long CurrencyID { get; set; }
        public Nullable<decimal> FromPrice { get; set; }
        public Nullable<decimal> ToPrice { get; set; }
        public string ViewInDate { get; set; }
        public string ViewOutDate { get; set; }
        public string HotelCheckIn { get; set; }
        public string HotelCheckOut { get; set; }
        public Nullable<long> LanguageID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<long> ModificationUserID { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string TourUrl { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual User1 User1 { get; set; }
        public virtual User1 User11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestTour> RequestTours { get; set; }
    }
}
