//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tpsa
    {
        public long ID { get; set; }
        public string CompanyID { get; set; }
        public string Name { get; set; }
        public string UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Pass { get; set; }
        public string PassNewHash { get; set; }
        public string PassO { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
    }
}
