//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferContract()
        {
            this.SpecialEquipPrefs1 = new HashSet<SpecialEquipPref>();
        }
    
        public long TransferContractid { get; set; }
        public string PickUpDateTime { get; set; }
        public string ReturnDateTime { get; set; }
        public string PickUpLoaction { get; set; }
        public string ReturnLocation { get; set; }
        public string IsoCurrency { get; set; }
        public string CitizenCountryName { get; set; }
        public Nullable<byte> DriverAge { get; set; }
        public Nullable<long> SpecialEquipPrefs { get; set; }
        public Nullable<long> ArrivalDetailsid { get; set; }
        public Nullable<long> PaymentCardid { get; set; }
        public Nullable<long> CompanyNameid { get; set; }
        public Nullable<long> Personid { get; set; }
        public Nullable<long> CarTotalFareid { get; set; }
        public Nullable<int> PassengerQty { get; set; }
        public long ContractID { get; set; }
        public string TransferRPH { get; set; }
        public string TransferRPHKey { get; set; }
        public string TransferTicket { get; set; }
        public string TransferBookingReferenceID { get; set; }
        public string BillTransferTicket { get; set; }
    
        public virtual ArrivalDetail ArrivalDetail { get; set; }
        public virtual CarTotalFare CarTotalFare { get; set; }
        public virtual CompanyName CompanyName { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual PaymentCard PaymentCard { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialEquipPref> SpecialEquipPrefs1 { get; set; }
    }
}
