//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSLocation
    {
        public long LocID { get; set; }
        public string Country { get; set; }
        public string RegionID { get; set; }
        public string Region { get; set; }
        public string ResortID { get; set; }
        public string Resort { get; set; }
    }
}
