//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSProperty
    {
        public string PropertyReferenceID { get; set; }
        public string PropertyName { get; set; }
        public Nullable<double> GeographyLevel3ID { get; set; }
        public Nullable<double> GeographyLevel2ID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TownCity { get; set; }
        public string County { get; set; }
        public Nullable<double> PostcodeZip { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }
        public Nullable<double> Fax { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Resort { get; set; }
        public string Region { get; set; }
        public string Country1 { get; set; }
        public string PropertyType { get; set; }
        public string PropertyGroup { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Airport { get; set; }
        public string ThumbnailURL { get; set; }
        public string Image1URL { get; set; }
        public string Image2URL { get; set; }
        public string Image3URL { get; set; }
        public string Image4URL { get; set; }
        public string Image5URL { get; set; }
        public string Image6URL { get; set; }
        public string Image7URL { get; set; }
        public string Image8URL { get; set; }
        public string Image9URL { get; set; }
        public string Image10URL { get; set; }
        public Nullable<double> ProductAttributes { get; set; }
        public string Description { get; set; }
        public long ID { get; set; }
    }
}
