//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserID { get; set; }
        public long CompanyID { get; set; }
        public long ContactID { get; set; }
        public long LanguageID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsAgancyUser { get; set; }
        public bool Active { get; set; }
        public byte CommisionPercent { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
    }
}
