//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPictureDic
    {
        public long UserPictureDicID { get; set; }
        public long UserID { get; set; }
        public long FromImageID { get; set; }
        public long ToImageID { get; set; }
        public long LastImageID { get; set; }
    }
}
