//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webservicex
    {
        public long WebservicexID { get; set; }
        public string AirportCode { get; set; }
        public string CityOrAirportName { get; set; }
        public string Country { get; set; }
        public string CountryAbbrviation { get; set; }
        public Nullable<long> CountryCode { get; set; }
        public Nullable<long> GMTOffset { get; set; }
        public Nullable<long> RunwayLengthFeet { get; set; }
        public Nullable<long> RunwayElevationFeet { get; set; }
        public Nullable<long> LatitudeDegree { get; set; }
        public Nullable<long> LatitudeMinute { get; set; }
        public Nullable<long> LatitudeSecond { get; set; }
        public string LatitudeNpeerS { get; set; }
        public Nullable<long> LongitudeDegree { get; set; }
        public Nullable<long> LongitudeMinute { get; set; }
        public Nullable<long> LongitudeSeconds { get; set; }
        public string LongitudeEperW { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
