//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.MapDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationAlternativeName
    {
        public long Id { get; set; }
        public long AccommodationID { get; set; }
        public string AlternativeName { get; set; }
        public string AlternativeNameType { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    }
}
