//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.MapDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationproviderXml
    {
        public long Rid { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<long> AccommodationlID { get; set; }
        public string providerXml { get; set; }
        public string VALUE { get; set; }
        public string providerCode { get; set; }
        public string providerType { get; set; }
        public string NAME { get; set; }
    }
}
