//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.MapDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationHotelsBed
    {
        public long LocationHotelsBedID { get; set; }
        public string Country { get; set; }
        public Nullable<long> RegionID { get; set; }
        public string Region { get; set; }
        public Nullable<long> ResortID { get; set; }
        public string Resort { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> LocationRegionID { get; set; }
        public Nullable<long> LocationResortID { get; set; }
    }
}
