//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.MapDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationLogTb
    {
        public int Id { get; set; }
        public Nullable<long> CityID { get; set; }
        public string NewName { get; set; }
        public string NewCountryCode { get; set; }
        public string NewCityName { get; set; }
        public string OldName { get; set; }
        public string OldCountryCode { get; set; }
        public string OldCityName { get; set; }
        public Nullable<long> LocationID { get; set; }
    }
}
