//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.MapDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblB
    {
        public long Bid { get; set; }
        public string Bdesc { get; set; }
        public Nullable<long> Bcount { get; set; }
        public Nullable<long> Btype { get; set; }
        public Nullable<System.DateTime> Bdate { get; set; }
        public string Bcode { get; set; }
        public Nullable<long> Brow { get; set; }
    }
}
